### ISSUE TITLE
Deploy Failure

### ISSUE THREAD

**Issue by Leomotors** [CunnyDev/saltyaom#11]
@Gusb3ll แก้ด้วยครับ

**Comment by Gusb3ll** [comment]
I forgor

**Comment by Leomotors** [comment]
> I forgor

💀

**Comment by SaltyAom** [comment]
Where @Gusb3ll

**Comment by Leomotors** [comment]
สมาชิกท่านใดถือ cloudflare

**Comment by Gusb3ll** [comment]
Gone

**Comment by Gusb3ll** [comment]
<img width="792" alt="image" src="https://github.com/CunnyDev/saltyaom/assets/77166960/971df26f-7174-43f4-9028-a94586101301">
@Leomotors
